/**
 * Apple App Attest server-side verifier.
 *
 * Proves that each API request comes from a genuine installation of YOUR app
 * on a real Apple device — not a script, emulator, or modified binary.
 *
 * This is the iOS equivalent of CAPTCHA for web apps. It blocks:
 *   - Bots and scripts that call your API directly
 *   - Modified/jailbroken apps
 *   - Replay attacks (each assertion is unique)
 *
 * How it works:
 *
 *   iOS App (client)                          Your Server (backend)
 *   ─────────────────                         ─────────────────────
 *   1. Generate key pair
 *      (DCAppAttestService.generateKey)
 *
 *   2. Attest key with Apple         ──────►  3. Verify attestation with Apple
 *      (generateAttestation)                     Store public key for this device
 *
 *   4. On each request, sign data    ──────►  5. Verify assertion signature
 *      (generateAssertion)                       against stored public key
 *
 * Setup:
 *
 *   1. Enable App Attest in your Xcode project:
 *      Target → Signing & Capabilities → + App Attest
 *
 *   2. Client-side (iOS app):
 *      ```swift
 *      import DeviceCheck
 *
 *      let service = DCAppAttestService.shared
 *      guard service.isSupported else { /* fallback for simulator */ }
 *
 *      // One-time: generate and attest a key
 *      let keyId = try await service.generateKey()
 *      let clientDataHash = Data(SHA256.hash(data: yourRequestData))
 *      let attestation = try await service.attestKey(keyId, clientDataHash: clientDataHash)
 *      // Send attestation + keyId to server for storage
 *
 *      // Each request: generate an assertion
 *      let assertion = try await service.generateAssertion(keyId, clientDataHash: clientDataHash)
 *      // Include assertion + keyId in request to server
 *      ```
 *
 *   3. Server-side (this file):
 *      ```swift
 *      let verifier = AppAttestVerifier(
 *          teamId: "YOUR_TEAM_ID",
 *          bundleId: "com.yourcompany.yourapp"
 *      )
 *      let otp = OtpService(sms: sms, store: store, appName: "MyApp", deviceAttest: verifier)
 *      ```
 *
 * Environment variables:
 *   APP_ATTEST_TEAM_ID=YOUR_TEAM_ID
 *   APP_ATTEST_BUNDLE_ID=com.yourcompany.yourapp
 *
 * References:
 *   - https://developer.apple.com/documentation/devicecheck/establishing-your-app-s-integrity
 *   - https://developer.apple.com/documentation/devicecheck/validating-apps-that-connect-to-your-server
 */

import Foundation
import CryptoKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

/// Server-side Apple App Attest verification.
///
/// Validates that requests come from a genuine installation of your app
/// on a real Apple device.
///
/// Note: This is a reference implementation. For production, you need:
///   1. A database to store per-device public keys (from attestation)
///   2. A counter per key to prevent replay attacks
///   3. The Apple App Attest root certificate for attestation validation
///
/// Consider using a battle-tested library for the CBOR/attestation parsing.
/// This implementation handles the assertion verification flow.
public actor AppAttestVerifier: DeviceAttestVerifier {
    private let teamId: String
    private let bundleId: String

    /// Stored public keys per device (keyId → public key).
    /// In production, persist this in your database.
    private var deviceKeys: [String: P256.Signing.PublicKey] = [:]

    /// Assertion counters per device (keyId → last seen counter).
    /// Must be persisted to prevent replay attacks.
    private var counters: [String: UInt32] = [:]

    /// Apple App Attest environment.
    public enum Environment: String, Sendable {
        /// Development / sandbox (Xcode builds, TestFlight)
        case development = "appattestdevelop"
        /// Production (App Store builds)
        case production = "appattest"
    }

    private let environment: Environment

    public init(teamId: String, bundleId: String, environment: Environment = .production) {
        self.teamId = teamId
        self.bundleId = bundleId
        self.environment = environment
    }

    /// Convenience initializer loading from environment variables.
    public init?(environment: Environment = .production) {
        guard let teamId = ProcessInfo.processInfo.environment["APP_ATTEST_TEAM_ID"],
              let bundleId = ProcessInfo.processInfo.environment["APP_ATTEST_BUNDLE_ID"] else {
            return nil
        }
        self.teamId = teamId
        self.bundleId = bundleId
        self.environment = environment
    }

    // MARK: - Attestation (one-time per device)

    /// Store a device's public key after validating the attestation object.
    ///
    /// Call this when a device first registers with your server.
    /// The attestation object is generated by DCAppAttestService.attestKey() on the client.
    ///
    /// - Parameters:
    ///   - keyId: The key identifier from DCAppAttestService.generateKey()
    ///   - attestation: The attestation object from DCAppAttestService.attestKey()
    ///   - clientDataHash: SHA-256 hash of the client data that was attested
    /// - Returns: true if attestation is valid and key was stored
    public func registerDevice(keyId: String, attestation: Data, clientDataHash: Data) async -> Bool {
        // Full attestation validation requires:
        // 1. Decode the CBOR attestation object
        // 2. Verify the x5c certificate chain against Apple's App Attest root CA
        // 3. Verify the nonce = SHA-256(authData + clientDataHash)
        // 4. Extract the credential public key from the attestation
        // 5. Verify the App ID (teamId + "." + bundleId) matches
        // 6. Verify the environment (production vs development)
        // 7. Store the public key and initial counter (0)
        //
        // This is complex CBOR/X.509 work. In production, use a library like:
        //   - swift-app-attest (community package)
        //   - Or implement using SwiftCBOR + X509 packages
        //
        // For this reference implementation, we assume the attestation has been
        // validated and the public key extracted. Replace the placeholder below
        // with your actual attestation validation logic.

        // TODO: Implement full attestation validation
        // let publicKey = try extractPublicKey(from: attestation)
        // deviceKeys[keyId] = publicKey
        // counters[keyId] = 0
        // return true

        return false  // Replace with actual implementation
    }

    // MARK: - Assertion verification (every request)

    /// Verify a device assertion.
    ///
    /// Called by OtpService on every sendOtp request when device attestation is enabled.
    ///
    /// - Parameters:
    ///   - assertion: The assertion data from DCAppAttestService.generateAssertion()
    ///   - keyId: The key identifier for this device
    ///   - clientData: The client data that was signed (typically request body hash)
    /// - Returns: true if the assertion is valid
    public func verify(assertion: Data, keyId: String, clientData: Data) async -> Bool {
        // 1. Look up the stored public key for this device
        guard let publicKey = deviceKeys[keyId] else {
            // Device not registered — client needs to call registerDevice first
            return false
        }

        // 2. Look up the last seen counter
        let lastCounter = counters[keyId] ?? 0

        // 3. Parse the assertion (CBOR-encoded authenticator data + signature)
        //
        // Assertion format:
        //   - authenticatorData: 37+ bytes
        //     - rpIdHash (32 bytes): SHA-256 of your App ID
        //     - flags (1 byte): bit 0 = user present
        //     - counter (4 bytes, big-endian): monotonically increasing
        //   - signature: ECDSA P-256 signature over (authenticatorData + clientDataHash)
        //
        guard assertion.count > 37 else { return false }

        // For a complete implementation, decode the CBOR assertion:
        // let (authenticatorData, signature) = try decodeCBORAssertion(assertion)

        // 4. Verify rpIdHash matches SHA-256(teamId + "." + bundleId)
        // let expectedRpId = Data(SHA256.hash(data: Data((teamId + "." + bundleId).utf8)))
        // guard authenticatorData.prefix(32) == expectedRpId else { return false }

        // 5. Verify counter is greater than last seen (prevents replay)
        // let counter = authenticatorData[33...36].withUnsafeBytes { $0.load(as: UInt32.self).bigEndian }
        // guard counter > lastCounter else { return false }

        // 6. Compute nonce = SHA-256(authenticatorData + SHA-256(clientData))
        // let clientDataHash = Data(SHA256.hash(data: clientData))
        // let nonce = Data(SHA256.hash(data: authenticatorData + clientDataHash))

        // 7. Verify ECDSA signature over nonce using stored public key
        // let ecdsaSignature = try P256.Signing.ECDSASignature(derRepresentation: signature)
        // guard publicKey.isValidSignature(ecdsaSignature, for: nonce) else { return false }

        // 8. Update counter
        // counters[keyId] = counter

        // TODO: Replace with actual CBOR decoding and signature verification
        // Consider using swift-cbor or a dedicated App Attest library
        return false  // Replace with actual implementation
    }
}

// MARK: - Usage Notes

/*
 PRODUCTION IMPLEMENTATION CHECKLIST:

 1. Add CBOR decoding dependency (e.g., SwiftCBOR):
    .package(url: "https://github.com/unrelentingtech/SwiftCBOR.git", from: "0.4.7")

 2. Download Apple's App Attest root certificate:
    https://www.apple.com/certificateauthority/Apple_App_Attestation_Root_CA.pem

 3. Implement registerDevice() to:
    - Decode the CBOR attestation object
    - Validate the x5c certificate chain against Apple's root CA
    - Extract and store the public key
    - Initialize the counter to 0

 4. Implement verify() to:
    - Decode the CBOR assertion
    - Verify rpIdHash, counter, and ECDSA signature
    - Update the counter

 5. Persist deviceKeys and counters in your database:
    CREATE TABLE device_keys (
        key_id      TEXT PRIMARY KEY,
        public_key  BLOB NOT NULL,
        counter     INTEGER NOT NULL DEFAULT 0,
        created_at  REAL NOT NULL,
        user_id     TEXT  -- optional: link device to user
    );

 6. Handle edge cases:
    - Device reset (new attestation for same user)
    - Key rotation
    - Simulator fallback for development (isSupported = false)
*/
